### ISSUE TITLE
access to link requires CWL authentication

### ISSUE THREAD

**Issue by brettdimond** [ubc-library-rc/awesome-digital-scholarship#1]
Accessing _A Guide to ORCID - Cambridge University Press (PDF)_ requires that I login using CWL. Is there another way to link to this resource that would allow it to be completely accessible by anyone?

**Comment by dohliam** [comment]
This is likely because you have Ezproxy or similar set up to automatically redirect links on cambridge.org. Accessing this guide does not require using a CWL (you can confirm this by opening the link in a Private/Incognito window, and/or turning off Ezproxy redirection in your browser).
