### ISSUE TITLE
possible candidate to add

### ISSUE THREAD

**Issue by brettdimond** [ubc-library-rc/awesome-digital-scholarship#3]
Many of these candidates may not be a good fit; for instance, some tend more toward the "specific tools" side of the spectrum, rather than the "knowledge domain" side. Additionally, some may be a bit dated and/or don't have many followers. However, to start, I thought I'd err on the side of being too broad, rather than too narrow. If you do decide to include some of the "tools" sites, there are more that could be incorporated.

**General research**
https://github.com/emptymalei/awesome-research
https://github.com/harpribot/awesome-information-retrieval
https://github.com/fasouto/awesome-dataviz
https://github.com/writing-resources/awesome-scientific-writing
https://github.com/nschloe/awesome-scientific-computing

**Learning**
https://programminghistorian.org/en/lessons/
https://github.com/siboehm/awesome-learn-datascience
https://carpentries.org/

**Linguistics and Natural Language Processing**
https://github.com/theimpossibleastronaut/awesome-linguistics
https://github.com/edobashira/speech-language-processing
https://github.com/arbox/nlp-with-ruby
https://github.com/dav009/awesome-spanish-nlp

**Data science**
https://github.com/academic/awesome-datascience
https://github.com/onurakpolat/awesome-bigdata
https://github.com/awesomedata/awesome-public-datasets
https://github.com/burningtree/awesome-json
https://github.com/jdorfman/awesome-json-datasets
https://github.com/tmcw/awesome-geojson
https://github.com/secretGeek/awesomeCSV
https://github.com/briatte/awesome-network-analysis

**Python**
https://github.com/vinta/awesome-python
https://github.com/krzjoa/awesome-python-data-science
https://github.com/faroit/awesome-python-scientific-audio

**R**
https://github.com/qinwf/awesome-R
https://github.com/RomanTsegelskyi/rbooks

**Julia**
https://github.com/svaksha/Julia.jl

**Git and GitHub**
https://github.com/arslanbilal/git-cheat-sheet
https://github.com/git-tips/tips
https://github.com/stevemao/awesome-git-addons
https://github.com/compscilauren/awesome-git-hooks
https://github.com/phillipadsmith/awesome-github
https://github.com/tiimgreen/github-cheat-sheet
https://github.com/sdras/awesome-actions
https://github.com/stefanbuck/awesome-browser-extensions-for-github

**Additional tools**
https://github.com/k4m4/terminals-are-sexy
https://github.com/janikvonrotz/awesome-powershell
https://github.com/agarrharr/awesome-cli-apps
https://github.com/veggiemonk/awesome-docker
https://github.com/ramitsurana/awesome-kubernetes
https://github.com/BubuAnabelas/awesome-markdown
https://github.com/dok/awesome-text-editing
https://github.com/dreikanter/sublime-bookmarks
https://github.com/mehcode/awesome-atom
https://github.com/markusschanta/awesome-jupyter

**Resources**
https://github.com/shime/creative-commons-media
https://github.com/44bits/awesome-opensource-documents
https://github.com/zachflower/awesome-open-source-supporters
https://github.com/dylanrees/citizen-science
https://github.com/terkelg/awesome-creative-coding
https://github.com/machinomy/awesome-non-financial-blockchain
https://github.com/alfred-workflows/awesome-alfred-workflows
https://github.com/matiassingers/awesome-readme

**Comment by dohliam** [comment]
@brettdimond Thanks very much for these suggestions! These all look good to me -- would you be interested in submitting a PR to add them directly?
