### ISSUE TITLE
Shall i create new category for some open source learning repos?

### ISSUE THREAD

**Issue by vedantbahel** [ubc-library-rc/awesome-digital-scholarship#4]
Shall I create a new category for some open-source learning repos?
Like this: https://github.com/microsoft/ML-For-Beginners

Not sure where it should be!

**Comment by dohliam** [comment]
Hi @vedantbahel thanks for the question! Contributions to the list are welcome so long as they have something to do with Digital Scholarship. I see you have closed the issue already though so perhaps this would be a better fit on a machine learning list?

**Comment by egrguric** [comment]
Hi @dohliam and @vedantbahel, just jumping in to say yes this is relevant and making a new category for OERs makes sense. @dohliam for context, the same DS team that started this list is continuing to contribute and currently teaching ML content.

**Comment by dohliam** [comment]
@egrguric Ah that makes sense -- thanks! Happy to see the list being updated :smile:
